name: Dispatch Update

on:
  push:
    paths:
      - 'README.md'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger target repository workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          https://api.github.com/repos/CarlosValladaresDiaz/any-helm-terraform-ek8-installer-2/actions/workflows/dispatch.yml/dispatches \
          -d '{"ref":"dev","inputs":{"branch":"dev","file_path":"README.md"}}'
